CREATE PROCEDURE
PROC_NEW_CUSTOMER (CUSTOMER_ID OUT NUMBER,
                   FIRST_NAME IN VARCHAR2,
                   CREDIT IN OUT NUMBER) IS
BEGIN

SELECT SEQ_CUSTOMER_ID.NEXTVAL INTO CUSTOMER_ID
FROM DUAL;

IF(CREDIT IS NULL) THEN
SELECT 100 INTO CREDIT
FROM DUAL;
END IF;

INSERT INTO CUSTOMER VALUES(CUSTOMER_ID,FIRST_NAME,CREDIT);

END PROC_NEW_CUSTOMER;

